# Usa la imagen base oficial de Nginx
FROM nginx:latest

# Copia el archivo de configuración personalizado de Nginx al contenedor
COPY ./nginx.conf /etc/nginx/nginx.conf

# Copia el contenido del sitio web al directorio predeterminado de Nginx
COPY ./site_content /usr/share/nginx/html

# Expon el puerto 80 para el servidor web Nginx
EXPOSE 80

# Comando para iniciar Nginx cuando se inicie el contenedor
CMD ["nginx", "-g", "daemon off;"]
